# Generated by Django 4.2.4 on 2023-08-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_tamagotchi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamagotchi',
            name='user',
        ),
    ]
